

name: CI

on: [deployment]

jobs:
    build:
  
      runs-on: ubuntu-latest
  
      steps:
      - uses: actions/checkout@v2
        with:
            ref: ${{ github.event.deployment.ref }}
      - name: Run a one-line script
        run: echo Deploying ${{ github.event.deployment.ref }} to ${{ github.event.deployment.environment  }}
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.